const northAmericaData = [
  { name: "Antigua & Barbuda", color: "red", counted: "yes" },
  { name: "Barbados", color: "red", counted: "yes" },
  { name: "Belize", color: "red", counted: "yes" },
  { name: "Canada", color: "green", counted: "yes" },
  { name: "Costa Rica", color: "red", counted: "yes" },
  { name: "Cuba", color: "red", counted: "yes" },
  { name: "Dominica", color: "red", counted: "yes" },
  { name: "Dominican Republic", color: "red", counted: "yes" },
  { name: "El Salvador", color: "red", counted: "yes" },
  { name: "Grenada", color: "red", counted: "yes" },
  { name: "Guatemala", color: "red", counted: "yes" },
  { name: "Haiti", color: "red", counted: "yes" },
  { name: "Honduras", color: "red", counted: "yes" },
  { name: "Jamaica", color: "red", counted: "yes" },
  { name: "Mexico", color: "red", counted: "yes" },
  { name: "Nicaragua", color: "red", counted: "yes" },
  { name: "Panama", color: "red", counted: "yes" },
  { name: "Saint Kitts and Nevis", color: "red", counted: "yes" },
  { name: "Saint Lucia", color: "red", counted: "yes" },
  { name: "Saint Vincent & The Grenadines", color: "red", counted: "yes" },
  { name: "The Bahamas", color: "red", counted: "yes" },
  { name: "Trinidad and Tobago", color: "red", counted: "yes" },
  { name: "United States", color: "green", counted: "yes" }
];

const southAmerica = [

  { name: "Argentina", color: "red", counted: true },
  { name: "Bolivia", color: "red", counted: true },
  { name: "Brazil", color: "red", counted: true },
  { name: "Chile", color: "red", counted: true },
  { name: "Colombia", color: "red", counted: true },
  { name: "Ecuador", color: "green", counted: true },
  { name: "Guyana", color: "red", counted: true },
  { name: "Paraguay", color: "red", counted: true },
  { name: "Peru", color: "red", counted: true },
  { name: "Suriname", color: "red", counted: true },
  { name: "Uruguay", color: "red", counted: true },
  { name: "Venezuela", color: "red", counted: true }

];

const europe = [

  { name: "Albania", color: "red", counted: true },
  { name: "Andorra", color: "red", counted: true },
  { name: "Austria", color: "red", counted: true },
  { name: "Belarus", color: "red", counted: true },
  { name: "Belgium", color: "red", counted: true },
  { name: "Bosnia & Herzegovina", color: "red", counted: true },
  { name: "Bulgaria", color: "red", counted: true },
  { name: "Croatia", color: "red", counted: true },
  { name: "Czechia", color: "red", counted: true },
  { name: "Denmark", color: "red", counted: true },
  { name: "Estonia", color: "red", counted: true },
  { name: "Finland", color: "red", counted: true },
  { name: "France", color: "green", counted: true },
  { name: "Germany", color: "red", counted: true },
  { name: "Greece", color: "green", counted: true },
  { name: "Hungary", color: "red", counted: true },
  { name: "Iceland", color: "red", counted: true },
  { name: "Ireland", color: "red", counted: true },
  { name: "Italy", color: "red", counted: true },
  { name: "Kosovo", color: "red", counted: true },
  { name: "Latvia", color: "red", counted: true },
  { name: "Liechtenstein", color: "red", counted: true },
  { name: "Lithuania", color: "red", counted: true },
  { name: "Luxembourg", color: "red", counted: true },
  { name: "Malta", color: "red", counted: true },
  { name: "Moldova", color: "red", counted: true },
  { name: "Monaco", color: "red", counted: true },
  { name: "Montenegro", color: "red", counted: true },
  { name: "Netherlands", color: "red", counted: true },
  { name: "North Macedonia", color: "red", counted: true },
  { name: "Norway", color: "red", counted: true },
  { name: "Poland", color: "red", counted: true },
  { name: "Portugal", color: "red", counted: true },
  { name: "Romania", color: "red", counted: true },
  { name: "Russia", color: "red", counted: true },
  { name: "San Marino", color: "red", counted: true },
  { name: "Serbia", color: "red", counted: true },
  { name: "Slovakia", color: "red", counted: true },
  { name: "Slovenia", color: "red", counted: true },
  { name: "Spain", color: "red", counted: true },
  { name: "Sweden", color: "red", counted: true },
  { name: "Switzerland", color: "green", counted: true },
  { name: "Ukraine", color: "red", counted: true },
  { name: "United Kingdom", color: "green", counted: true },
  { name: "Vatican City", color: "red", counted: true }

];

const africaData = [
  { name: "Algeria", color: "red", counted: "yes" },
  { name: "Angola", color: "red", counted: "yes" },
  { name: "Benin", color: "red", counted: "yes" },
  { name: "Botswana", color: "red", counted: "yes" },
  { name: "Burkina Faso", color: "red", counted: "yes" },
  { name: "Burundi", color: "red", counted: "yes" },
  { name: "Cameroon", color: "red", counted: "yes" },
  { name: "Cape Verde", color: "red", counted: "yes" },
  { name: "Central African Republic", color: "red", counted: "yes" },
  { name: "Chad", color: "red", counted: "yes" },
  { name: "Comoros", color: "red", counted: "yes" },
  { name: "D.R. Congo", color: "red", counted: "yes" },
  { name: "Djibouti", color: "red", counted: "yes" },
  { name: "Egypt", color: "red", counted: "yes" },
  { name: "Equatorial Guinea", color: "red", counted: "yes" },
  { name: "Eritrea", color: "red", counted: "yes" },
  { name: "Eswatini", color: "red", counted: "yes" },
  { name: "Ethiopia", color: "red", counted: "yes" },
  { name: "Gabon", color: "red", counted: "yes" },
  { name: "Ghana", color: "red", counted: "yes" },
  { name: "Guinea", color: "red", counted: "yes" },
  { name: "Guinea Bissau", color: "red", counted: "yes" },
  { name: "Ivory Coast", color: "red", counted: "yes" },
  { name: "Kenya", color: "red", counted: "yes" },
  { name: "Lesotho", color: "red", counted: "yes" },
  { name: "Liberia", color: "red", counted: "yes" },
  { name: "Libya", color: "red", counted: "yes" },
  { name: "Madagascar", color: "red", counted: "yes" },
  { name: "Malawi", color: "red", counted: "yes" },
  { name: "Mali", color: "red", counted: "yes" },
  { name: "Mauritania", color: "red", counted: "yes" },
  { name: "Mauritius", color: "red", counted: "yes" },
  { name: "Morocco", color: "red", counted: "yes" },
  { name: "Mozambique", color: "red", counted: "yes" },
  { name: "Namibia", color: "red", counted: "yes" },
  { name: "Niger", color: "red", counted: "yes" },
  { name: "Nigeria", color: "red", counted: "yes" },
  { name: "Republic of Congo", color: "red", counted: "yes" },
  { name: "Rwanda", color: "red", counted: "yes" },
  { name: "São Tomé and Principe", color: "red", counted: "yes" },
  { name: "Senegal", color: "red", counted: "yes" },
  { name: "Seychelles", color: "red", counted: "yes" },
  { name: "Sierra Leone", color: "red", counted: "yes" },
  { name: "Somalia", color: "red", counted: "yes" },
  { name: "South Africa", color: "red", counted: "yes" },
  { name: "South Sudan", color: "red", counted: "yes" },
  { name: "Sudan", color: "red", counted: "yes" },
  { name: "Tanzania", color: "red", counted: "yes" },
  { name: "The Gambia", color: "red", counted: "yes" },
  { name: "Togo", color: "red", counted: "yes" },
  { name: "Tunisia", color: "red", counted: "yes" },
  { name: "Uganda", color: "red", counted: "yes" },
  { name: "Zambia", color: "red", counted: "yes" },
  { name: "Zimbabwe", color: "red", counted: "yes" }
];

const westAsiaData = [
  { name: "Afghanistan", color: "red", counted: "yes" },
  { name: "Armenia", color: "red", counted: "yes" },
  { name: "Azerbaijan", color: "red", counted: "yes" },
  { name: "Bahrain", color: "red", counted: "yes" },
  { name: "Cyprus", color: "green", counted: "yes" },
  { name: "Georgia", color: "red", counted: "yes" },
  { name: "Iran", color: "red", counted: "yes" },
  { name: "Iraq", color: "red", counted: "yes" },
  { name: "Israel", color: "red", counted: "yes" },
  { name: "Jordan", color: "red", counted: "yes" },
  { name: "Kuwait", color: "red", counted: "yes" },
  { name: "Lebanon", color: "red", counted: "yes" },
  { name: "Oman", color: "red", counted: "yes" },
  { name: "Palestine", color: "red", counted: "yes" },
  { name: "Qatar", color: "red", counted: "yes" },
  { name: "Saudi Arabia", color: "red", counted: "yes" },
  { name: "Syria", color: "red", counted: "yes" },
  { name: "Turkey", color: "red", counted: "yes" },
  { name: "United Arab Emirates", color: "red", counted: "yes" },
  { name: "Yemen", color: "red", counted: "yes" }
];

const asiaData = [
  { name: "Bangladesh", color: "red", counted: "yes" },
  { name: "Bhutan", color: "red", counted: "yes" },
  { name: "Brunei", color: "red", counted: "yes" },
  { name: "Cambodia", color: "red", counted: "yes" },
  { name: "China", color: "red", counted: "yes" },
  { name: "India", color: "red", counted: "yes" },
  { name: "Indonesia", color: "red", counted: "yes" },
  { name: "Japan", color: "red", counted: "yes" },
  { name: "Kazakhstan", color: "red", counted: "yes" },
  { name: "Kyrgyzstan", color: "red", counted: "yes" },
  { name: "Laos", color: "red", counted: "yes" },
  { name: "Malaysia", color: "red", counted: "yes" },
  { name: "Maldives", color: "red", counted: "yes" },
  { name: "Mongolia", color: "red", counted: "yes" },
  { name: "Myanmar", color: "red", counted: "yes" },
  { name: "Nepal", color: "red", counted: "yes" },
  { name: "North Korea", color: "red", counted: "yes" },
  { name: "Pakistan", color: "red", counted: "yes" },
  { name: "Philippines", color: "red", counted: "yes" },
  { name: "Singapore", color: "red", counted: "yes" },
  { name: "South Korea", color: "red", counted: "yes" },
  { name: "Sri Lanka", color: "red", counted: "yes" },
  { name: "Taiwan", color: "red", counted: "yes" },
  { name: "Tajikistan", color: "red", counted: "yes" },
  { name: "Thailand", color: "red", counted: "yes" },
  { name: "Timor-Leste", color: "red", counted: "yes" },
  { name: "Turkmenistan", color: "red", counted: "yes" },
  { name: "Uzbekistan", color: "red", counted: "yes" },
  { name: "Vietnam", color: "red", counted: "yes" }
];

const oceaniaData = [
  { name: "Australia", color: "red", counted: "yes" },
  { name: "Fiji", color: "red", counted: "yes" },
  { name: "Kiribati", color: "red", counted: "yes" },
  { name: "Marshall Islands", color: "red", counted: "yes" },
  { name: "Micronesia", color: "red", counted: "yes" },
  { name: "Nauru", color: "red", counted: "yes" },
  { name: "New Zealand", color: "red", counted: "yes" },
  { name: "Palau", color: "red", counted: "yes" },
  { name: "Papua New Guinea", color: "red", counted: "yes" },
  { name: "Samoa", color: "red", counted: "yes" },
  { name: "Solomon Islands", color: "red", counted: "yes" },
  { name: "Tonga", color: "red", counted: "yes" },
  
  { name: "Tuvalu", color: "red", counted: "yes" },
  { name: "Vanuatu", color: "red", counted: "yes" }
];