const statesData = [
  { name: "Alabama", color: "green" },
  { name: "Alaska", color: "red" },
  { name: "Arizona", color: "green" },
  { name: "Arkansas", color: "green" },
  { name: "California", color: "red" },
  { name: "Colorado", color: "green" },
  { name: "Connecticut", color: "green" },
  { name: "Delaware", color: "green" },
  { name: "Florida", color: "green" },
  { name: "Georgia", color: "red" },
  { name: "Hawaii", color: "red" },
  { name: "Idaho", color: "red" },
  { name: "Illinois", color: "green" },
  { name: "Indiana", color: "green" },
  { name: "Iowa", color: "green" },
  { name: "Kansas", color: "green" },
  { name: "Kentucky", color: "green" },
  { name: "Louisiana", color: "green" },
  { name: "Maine", color: "red" },
  { name: "Maryland", color: "green" },
  { name: "Massachusetts", color: "green" },
  { name: "Michigan", color: "green" },
  { name: "Minnesota", color: "red" },
  { name: "Mississippi", color: "green" },
  { name: "Missouri", color: "green" },
  { name: "Montana", color: "red" },
  { name: "Nebraska", color: "green" },
  { name: "Nevada", color: "red" },
  { name: "New Hampshire", color: "red" },
  { name: "New Jersey", color: "red" },
  { name: "New Mexico", color: "green" },
  { name: "New York", color: "green" },
  { name: "North Carolina", color: "green" },
  { name: "North Dakota", color: "green" },
  { name: "Ohio", color: "green" },
  { name: "Oklahoma", color: "green" },
  { name: "Oregon", color: "red" },
  { name: "Pennsylvania", color: "red" },
  { name: "Rhode Island", color: "green" },
  { name: "South Carolina", color: "red" },
  { name: "South Dakota", color: "green" },
  { name: "Tennessee", color: "green" },
  { name: "Texas", color: "green" },
  { name: "Utah", color: "green" },
  { name: "Vermont", color: "red" },
  { name: "Virginia", color: "green" },
  { name: "Washington", color: "red" },
  { name: "West Virginia", color: "green" },
  { name: "Wisconsin", color: "red" },
  { name: "Wyoming", color: "green" }
];

const territoriesData = [
  { name: "Washington, D.C.", color: "red" },
  { name: "Puerto Rico", color: "red" },
  { name: "Guam", color: "red" },
  { name: "U.S. Virgin Islands", color: "red" },
  { name: "American Samoa", color: "red" },
  { name: "Northern Mariana Islands", color: "red" }
];